name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_cross: true

          - name: macos
            os: macos-latest
            target: x86_64-apple-darwin
            use_cross: false

          - name: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            use_cross: false

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (manual)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup show

      - name: Install target (macOS only)
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          rustup target add x86_64-apple-darwin

      - name: Install Cross (Linux only)
        if: matrix.use_cross == true
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Install cargo-deb (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: cargo install cargo-deb

      - name: Build (Cross for Linux)
        if: matrix.use_cross == true
        run: |
          cross build --release --target ${{ matrix.target }}

      - name: Build (Native for Mac/Windows)
        if: matrix.use_cross == false
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Package .deb (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo deb --no-build --target ${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: markit-${{ matrix.name }}
          path: |
            target/${{ matrix.target }}/release/markit*
            target/${{ matrix.target }}/release/markit.exe
            target/${{ matrix.target }}/debian/*.deb

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "${{ github.ref_name }}"
          files: |
            target/x86_64-unknown-linux-gnu/release/markit
            target/x86_64-unknown-linux-gnu/debian/*.deb
            target/x86_64-apple-darwin/release/markit
            target/x86_64-pc-windows-msvc/release/markit.exe
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}

  publish:
    name: Publish Crate
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (manual)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          rustup show

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Dispatch Homebrew bump
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
          repository: Nightstack/homebrew-markit
          event-type: bump-homebrew
          client-payload: '{"tag": "${{ github.ref_name }}"}'
