name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_cross: true

          - name: macos
            os: macos-latest
            target: x86_64-apple-darwin
            use_cross: false

          - name: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            use_cross: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Cross (Linux only)
        if: matrix.use_cross == true
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build (Cross for Linux)
        if: matrix.use_cross == true
        run: |
          cross build --release --target ${{ matrix.target }}

      - name: Build (Native for Mac/Windows)
        if: matrix.use_cross == false
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: markit-${{ matrix.name }}
          path: |
            target/${{ matrix.target }}/release/markit*
            target/${{ matrix.target }}/release/markit.exe

  publish:
    name: Publish Crate
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Dispatch Homebrew bump
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: Nightstack/homebrew-markit
          event-type: bump-homebrew
          client-payload: '{"tag": "v${{ github.ref_name }}"}'
